data_root: './images/dataset'
analyzing:
  b_thr: 2
server: './server'
bulb:
  url: './bulb'
  host: '
  colors:
    'spring1': [0, 255, 0]
    'spring2': [0, 255, 0]
    'spring3': [0, 255, 0]
    'summer1': [255, 255, 0]
    'summer2': [255, 255, 0]
    'summer3': [255, 255, 0]
    'fall1': [255, 0, 0]
    'fall2': [255, 0, 0]
    'fall3': [255, 0, 0]
    'winter1': [0, 0, 255]
    'winter2': [0, 0, 255]
    'winter3': [0, 0, 255]
    'default': [255, 255, 255]